stages:
  ingestion:
    cmd: >
      python src/ingestion.py 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_now.csv" 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_recent.csv" 
      "data/intermediate/lastweek_17112025.csv"
    deps:
      - src/ingestion.py
    outs:
      - data/intermediate
  prepare:
    cmd: >
      python src/prepare.py
      data/intermediate/lastweek_17112025.csv
      data/raw/ogd-smn_meta_parameters.csv
      data/prepared
    deps:
      - params.yaml
      - data/raw
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/prepared
  train:
    cmd: >
      python src/train.py
      data/prepared/train.parquet
      data/prepared/test.parquet
    deps:
      - params.yaml
      - src/train.py
      - src/utils/seed.py
      - data/prepared/train.parquet
      - data/prepared/test.parquet
    outs:
      - model/air_temperature_regressor.bentomodel
      - evaluation/plots/train_history.png
  evaluate:
    cmd: >
      python src/evaluate.py
      model/air_temperature_regressor.bentomodel
      data/prepared/test.parquet
    deps:
      - src/evaluate.py
      - model/air_temperature_regressor.bentomodel
      - data/prepared/test.parquet
    plots:
      - evaluation/plots/prediction_preview.png
    outs:
      - evaluation/metrics.json
