stages:
  ingestion:
    cmd: >
      python src/ingestion.py 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_now.csv" 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_recent.csv" 
      "data/intermediate"
    deps:
      - src/ingestion.py
    outs:
      - data/intermediate
  prepare:
    cmd: >
      python src/prepare.py
<<<<<<< HEAD
=======
      data/raw/ogd-smn_puy_h_recent.csv
>>>>>>> 62bdf34111b07507d418a4b8453621b8b28b544f
      data/intermediate
      data/raw/ogd-smn_meta_parameters.csv
      data/prepared
    deps:
      - params.yaml
      - data/raw
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/prepared
  train:
    cmd: >
      python src/train.py
      data/prepared/train_historical.parquet
      data/prepared/val_historical.parquet
      data/prepared/train_finetuning.parquet
      data/prepared/val_finetuning.parquet
    deps:
      - params.yaml
      - src/train.py
      - src/utils/seed.py
<<<<<<< HEAD
      - data/prepared/train.parquet
      - data/prepared/test.parquet
=======
      - data/prepared/train_historical.parquet
      - data/prepared/val_historical.parquet
      - data/prepared/train_finetuning.parquet
      - data/prepared/val_finetuning.parquet
>>>>>>> 62bdf34111b07507d418a4b8453621b8b28b544f
    outs:
      - model/model.bentomodel
      - evaluation/plots/train_history.png
  evaluate:
    cmd: >
      python src/evaluate.py
      model/model.bentomodel
      data/prepared/val_historical.parquet
      data/prepared/val_finetuning.parquet
    deps:
      - src/evaluate.py
      - model/model.bentomodel
      - data/prepared/val_historical.parquet
      - data/prepared/val_finetuning.parquet
    plots:
      - evaluation/plots/finetuned_model_finetuning_validation.png
      - evaluation/plots/finetuned_model_historical_validation.png
    outs:
      - evaluation/metrics.json
