stages:
  ingestion:
    cmd: >
      python src/ingestion.py 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_now.csv" 
      "https://data.geo.admin.ch/ch.meteoschweiz.ogd-smn/puy/ogd-smn_puy_h_recent.csv" 
      "data/intermediate"
    deps:
      - src/ingestion.py
    outs:
      - data/intermediate
  prepare:
    cmd: >
      python src/prepare.py
      data/raw/ogd-smn_puy_h_recent.csv
      data/intermediate
      data/raw/ogd-smn_meta_parameters.csv
      data/prepared
    deps:
      - params.yaml
      - data/raw
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/prepared
  train_baseline:
    cmd: >
      python src/train_baseline.py
      data/prepared/train_historical.parquet
      data/prepared/val_historical.parquet
    params:
      - train.seed
      - train.learning_rate
      - train.loss
      - train.n_epochs
      - train.batch_size
    deps:
      - params.yaml
      - src/train_baseline.py
      - src/utils/seed.py
      - src/utils/train_utils.py
      - data/prepared/train_historical.parquet
      - data/prepared/val_historical.parquet
    outs:
      - model/baseline.bentomodel
      - evaluation/plots/baseline_train_history.png
  train:
    cmd: >
      python src/train.py
      data/prepared/train_historical.parquet
      data/prepared/val_historical.parquet
      data/prepared/train_finetuning.parquet
      data/prepared/val_finetuning.parquet
    params:
      - train.seed
      - train.learning_rate
      - train.loss
      - train.n_epochs
      - train.batch_size
    deps:
      - params.yaml
      - src/train.py
      - src/utils/seed.py
      - src/utils/train_utils.py
      - data/prepared/train_historical.parquet
      - data/prepared/val_historical.parquet
      - data/prepared/train_finetuning.parquet
      - data/prepared/val_finetuning.parquet
      - model/baseline.bentomodel
    outs:
      - model/model.bentomodel
      - evaluation/plots/train_history.png

  evaluate:
    cmd: >
      python src/evaluate.py
      model/model.bentomodel
      data/prepared/val_historical.parquet
      data/prepared/val_finetuning.parquet
    deps:
      - src/evaluate.py
      - model/model.bentomodel
      - data/prepared/val_historical.parquet
      - data/prepared/val_finetuning.parquet
    plots:
      - evaluation/plots/finetuned_model_finetuning_validation.png
      - evaluation/plots/finetuned_model_historical_validation.png
    metrics:
      - evaluation/metrics.json
