prepare:
  separator_train_val: 0.8
train_baseline:
  seed: 713705
  n_neurons1: 8
  n_neurons2: 4
  dropout: 0.1
  activation: gelu
  kernel_initializer: he_normal
  learning_rate: 0.001
  loss: mse
  n_epochs: 20
  batch_size: 16
train:
  seed: 713705
  learning_rate: 0.001
  loss: mse
  n_epochs: 20
  batch_size: 16
  lwf_weight: 0
  replay_ratio: 0.1