apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-temperature-regressor-deployment
  labels:
    app: air-temperature-regressor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: air-temperature-regressor
  template:
    metadata:
      labels:
        app: air-temperature-regressor
    spec:
      containers:
        - name: air-temperature-regressor
          image: europe-west6-docker.pkg.dev/mlops-miss-meteo/miss-meteo-registry/air-temperature-regressor:latest
