name: continuous_learning

on:
#  schedule:
#    - cron: "0 9 * * 1"     # Every Monday at 09:00 UTC
  push:
    branches:
      - '**'   # Run on any push (to test the workflow)
  workflow_dispatch:         # Allow manual trigger


jobs:
  ingest_new_data_and_pull_request:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt

      - name: Ingest new data
        run: dvc repro ingestion
      - name: Add changes to git
        run: git add .

      - name: Create Pull Request # Pull request will automatically trigger model retraining workflow
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-retrain model"
          branch: retrain-${{ github.run_number }}
          base: main
          title: "Automated model retraining"
          body: |
            This PR contains changes from automated model retraining.
            - Triggered via schedule/dispatch
            - Generated by GitHub Actions + DVC
