name: MLOps CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  train:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show disk usage
        run: |
          df -h

      - name: Setup MLOps Env
        uses: ./.github/actions/setup-mlops
        with:
          gcp_credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install --requirement requirements-freeze.txt

      - name: Show disk usage
        run: |
          df -h

      - name: Pull Data
        run: dvc pull

      - name: Show disk usage
        run: |
          df -h

      - name: Reproduce Pipeline (No Ingestion)
        run: dvc repro -f prepare train_baseline train evaluate

      - name: Push Artifacts to DVC & Commit Lock
        if: (github.event_name == 'push') && (github.ref != 'refs/heads/main')
        run: |
          dvc push
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add dvc.lock
          git commit -m "feat(model): update model artifacts"
          git push
          

      - name: Upload BentoModel artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-bentomodel
          path: model/baseline.bentomodel
          overwrite: true

      - name: Upload evaluation metrics
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-metrics
          path: evaluation/*
          overwrite: true

      - name: Show disk usage
        run: |
          df -h

  cml:
    needs: train
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          pip install dvc==3.60.1

      - name: Setup CML
        uses: iterative/setup-cml@v2
        with:
          version: '0.20.6'

      - name: Download metrics
        uses: actions/download-artifact@v4
        with:
          name: evaluation-metrics
          path: evaluation

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all other Git branches
          git fetch --depth=1 origin main:main
          
          echo "# Model Performance Report" > report.md
          
          echo "## Params workflow vs. main" >> report.md
          dvc params diff main --md >> report.md
          
          echo "## Metrics workflow vs. main" >> report.md
          dvc metrics diff main --md >> report.md
          
          echo "## Training plot" >> report.md
          echo '![](evaluation/plots/baseline_train_history.png "baseline_model_training")' >> report.md
          echo '![](evaluation/plots/train_history.png "retrained_model_training")' >> report.md
          
          echo "## Validation on New dataset" >> report.md
          echo '![](evaluation/plots/baseline_model_finetuning_validation.png "baseline_model_new_validation")' >> report.md
          echo '![](evaluation/plots/finetuned_model_finetuning_validation.png "retrained_model_new_validation")' >> report.md

          echo "## Validation on Historical dataset" >> report.md
          echo '![](evaluation/plots/baseline_model_historical_validation.png "baseline_model_historical_validation")' >> report.md
          echo '![](evaluation/plots/finetuned_model_historical_validation.png "retrained_model_historical_validation")' >> report.md
          
          cml comment update --target=pr --publish report.md

  deploy:
    needs: train
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Show disk usage
        run: |
          df -h

      - name: Setup MLOps Env
        uses: ./.github/actions/setup-mlops
        with:
          gcp_credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install --requirement requirements-deployment-freeze.txt

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}
          username: _json_key
          password: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Download BentoModel artifact
        uses: actions/download-artifact@v4
        with:
          name: baseline-bentomodel
          path: model

      - name: Show disk usage
        run: |
          df -h

      - name: Import the BentoML model
        run: |
          bentoml models import model/baseline.bentomodel

      - name: Show disk usage
        run: |
          df -h

      - name: Build the BentoML model artifact
        run: |
          bentoml build src
          bentoml list
          bentoml models list
          

      - name: Show disk usage
        run: |
          df -h

      - name: Containerize and publish the BentoML model artifact Docker image
        run: |
          bentoml containerize air_temperature_regressor:latest \
            --image-tag ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/air-temperature-regressor:latest \
            --image-tag ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/air-temperature-regressor:${{ github.sha }}
          
          docker push --all-tags ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/air-temperature-regressor

      - name: Show disk usage
        run: |
          df -h

      - name: Get Google Cloud's Kubernetes credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ secrets.GCP_K8S_CLUSTER_NAME }}
          location: ${{ secrets.GCP_K8S_CLUSTER_ZONE }}

      - name: Update the Kubernetes deployment image in `kubernetes/deployment.yaml`
        env:
          IMAGE_TAG: ${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}/air-temperature-regressor:${{ github.sha }}
        run: |
          echo "Updating image to: $IMAGE_TAG"
          yq -i ".spec.template.spec.containers[0].image = env(IMAGE_TAG)" kubernetes/deployment.yaml
          cat kubernetes/deployment.yaml

      - name: Deploy the model on Kubernetes
        run: |
          kubectl apply \
            -f kubernetes/deployment.yaml \
            -f kubernetes/service.yaml