name: Weekly Data Ingestion

on:
  schedule:
    - cron: '0 */1 * * *' # every hour updating (to test our implementation)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ingest_and_pr:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/machledata/machledata_miss_meteo/mlops-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new branch
        run: |
          BRANCH_NAME="continuous-learning/retrain-$(date +%Y%m%d-%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"

      - name: Pull Data
        run: dvc pull

      - name: Ingest New Data
        run: dvc repro -f

      - name: Push Data to DVC Remote
        run: dvc push

      - name: Commit Lock and Push
        id: git_push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dvc.lock
          git commit -m "feat(dvc): weekly ingestion update"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_PR_UPDATE_DATA }}
        run: |
          gh pr create \
            --title "Continuous Learning: Model Retrain $(date +%Y-%m-%d)" \
            --body "This PR creates a new model training cycle based on the latest data ingestion." \
            --base main \
            --head ${{ env.BRANCH_NAME }}